### ISSUE TITLE
关于后台文章修改权限，可以调用内置方法

### ISSUE THREAD

**Issue by horsun** [laiqun/clean_blog#1]
可以在admin定制化对应的类里面添加下面方法
```python
def has_change_permission(self, org_obj=None):
    if self.request.user == org_obj.author:
        return True
```
此外还有 ` has_add_permission()` 和`has_delete_permission()`用法相类似 参数为 `self`和 `obj`

**Comment by laiqun** [comment]
hi horsun经过试验，下面的函数就可以控制显示、修改、删除的行为。这三种行为都会调用下面的函数来获取文件，如果不是自己的文章，根本获取不到的。xadmin的写法和admin有所不同，要写成query_set。
这些是经过试验得知的。
``python
class MyModelAdmin(admin.ModelAdmin):
  def get_queryset(self, request):
      qs = super(MyModelAdmin, self).get_queryset(request)
      if request.user.is_superuser:#超级用户可以获得全部文章
          return qs
      else:
          return qs.filter(author=request.user)#只显示自己发布的问
```
